export const characters = {
  character: {
    "tck_wzh": {
      sex: "male",
      group: "tck_302",
      hp: 3,
      maxHp: 3,
      skills: ["tck_lao_dong_zhi_xing", "tck_gou_yan_can_chuan"],
      img: "extension/TCK/imgs/charactors/tck_wzh.jpg",
    },
    "tck_xing_wzh": {
      sex: "male",
      group: "tck_qi",
      hp: 4,
      maxHp: 4,
      skills: ["tck_gao_xiao"],
      img: "extension/TCK/imgs/charactors/tck_xing_wzh.jpg",
    },
    "tch_hwj_wzh": {
      sex: "male",
      group: "qun",
      hp: 3,
      maxHp: 3,
      skills: ["tck_lao_dong_zui_guang_rong", "tck_bu_lao_er_huo", "tck_bu_zhi_hao_dai"],
      img: "extension/TCK/imgs/charactors/tch_hwj_wzh.jpg",
    },
    "tck_yzxd_wzh": {
      sex: "male",
      group: "tck_shu",
      hp: 4,
      maxHp: 4,
      skills: ["tck_pa_si"],
      img: "extension/TCK/imgs/charactors/tck_yzxd_wzh.jpg",
    },
    "tck_gh": {
      sex: "male",
      group: "tck_yong",
      hp: 3,
      maxHp: 3,
      skills: ["tck_ji_ta", "tck_ge_sheng_wai_fang"],
      img: "extension/TCK/imgs/charactors/tck_gh.jpg",
    },
    "tck_scp_173": {
      sex: "none",
      group: "tck_shou",
      hp: 4,
      maxHp: 4,
      skills: ["tck_zhu_shi", "tck_ning_bo"],
      img: "extension/TCK/imgs/charactors/tck_scp_173.jpg",
    },
    "tck_hj_caozhang": {
      sex: "male",
      group: "wei",
      hp: 6,
      maxHp: 6,
      skills: ["tck_hj_jiang_chi"],
      img: "extension/TCK/imgs/charactors/tck_hj_caozhang.jpg",
    },
    "tck_hj_weiyan": {
      sex: "male",
      group: "shu",
      hp: 4,
      maxHp: 4,
      skills: ["tck_hj_kuang_gu"],
      img: "extension/TCK/imgs/charactors/tck_hj_weiyan.jpg",
    },
    "tck_hj_huanggai": {
      sex: "male",
      group: "wu",
      hp: 4,
      maxHp: 4,
      skills: ["tck_hj_tian_rou"],
      img: "extension/TCK/imgs/charactors/tck_hj_huanggai.jpg",
    },
    "tck_hxc": {
      sex: "male",
      group: "tck_jiang",
      hp: 4,
      maxHp: 4,
      skills: ["tck_ji_qi_shi", "tck_ji_qian_feng", "tck_qiu_chang_ji_qing"],
      img: "extension/TCK/imgs/charactors/tck_hxc.jpg",
    },
    "tck_yjc": {
      sex: "male",
      group: "tck_605",
      hp: 4,
      maxHp: 4,
      skills: ["tck_chang", "tck_tiao", "tck_rap", "tck_lan_qiu"],
      img: "extension/TCK/imgs/charactors/tck_yjc.jpg",
    },
    "tck_pmk_ailian": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 3,
      maxHp: 3,
      skills: ["tck_pin_min", "tck_ai_xin"],
      img: "extension/TCK/imgs/charactors/tck_pmk_ailian.jpg",
    },
    "tck_rkshs_IB": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 0,
      maxHp: 0,
      skills: ["tck_mei_gui", "tck_xiao_hai"],
      img: "extension/TCK/imgs/charactors/tck_rkshs_IB.jpg",
    },
    "tck_aoerjia": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_gan_shen_me_a_?", "tck_bin_si", "tck_xi_wang"],
      img: "extension/TCK/imgs/charactors/tck_aoerjia.jpg",
    },
    "tck_marry": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 5,
      maxHp: 5,
      skills: ["tck_ju_huo", "tck_qi_pian"],
      img: "extension/TCK/imgs/charactors/tck_marry.jpg",
    },
    "tck_sp_sunshangxiang": {
      sex: "female",
      group: "tck_sp",
      hp: 3,
      maxHp: 3,
      skills: ["tck_fan_xiang", "liangzhu"],
      img: "extension/TCK/imgs/charactors/tck_sp_sunshangxiang.jpg",
    },
    "tck_scp_035": {
      sex: "none",
      group: "tck_shou",
      hp: 5,
      maxHp: 5,
      skills: ["tck_diu_shi"],
      img: "extension/TCK/imgs/charactors/tck_scp_035.jpg",
    },
    "tck_spc_173": {
      sex: "male",
      group: "tck_shou",
      hp: 4,
      maxHp: 4,
      skills: ["tck_xue_xi", "tck_ji_lei_0"],
      img: "extension/TCK/imgs/charactors/tck_spc_173.jpg",
    },
    "tck_ban": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 3,
      maxHp: 3,
      skills: ["tck_hui_fu", "tck_bao_hu"],
      img: "extension/TCK/imgs/charactors/tck_ban.jpg",
    },
    "tck_rkshs_fuchuangzi": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_yi_yu", "tck_zi_sha"],
      img: "extension/TCK/imgs/charactors/tck_rkshs_fuchuangzi.jpg",
    },
    "tck_bachidaren": {
      sex: "female",
      group: "tck_guai_qi",
      hp: 3,
      maxHp: 3,
      skills: ["tck_mi_huo", "tck_xi_shou"],
      img: "extension/TCK/imgs/charactors/tck_bachidaren.jpg",
    },
    "tck_wuyumolisha": {
      sex: "female",
      group: "tck_dong",
      hp: 3,
      maxHp: 3,
      skills: ["tck_ji_xian_huo_hua", "tck_fei_zhi_xiang_xing_guang_xian", "tck_wu_yu"],
      img: "extension/TCK/imgs/charactors/tck_wuyumolisha.jpg",
    },
    "tck_fhz": {
      sex: "male",
      group: "tck_604",
      hp: 1,
      maxHp: 1,
      skills: ["tck_xie_sheng", "tck_hui_meng", "tck_bian_shen"],
      img: "extension/TCK/imgs/charactors/tck_fhz.jpg",
    },
    "tck_guanyu_zhangfei": {
      sex: "male",
      group: "shu",
      hp: 4,
      maxHp: 4,
      skills: ["paoxiao", "wusheng"],
      img: "extension/TCK/imgs/charactors/tck_guanyu_zhangfei.jpg",
    },
    "tck_scp_001_wjlt": {
      sex: "none",
      group: "tck_shou",
      hp: 3,
      maxHp: 3,
      skills: ["tck_xun_huan", "tck_lun_hui"],
      img: "extension/TCK/imgs/charactors/tck_scp_001_wjlt.jpg",
    },
    "tck_fengfeisha": {
      sex: "male",
      group: "tck_ming",
      hp: 2,
      maxHp: 2,
      skills: ["tck_fei_sha", "tck_gu"],
      img: "extension/TCK/imgs/charactors/tck_fengfeisha.jpg",
    },
    "tck_jiutuntongzi": {
      sex: "male",
      group: "tck_gui",
      hp: 3,
      maxHp: 3,
      skills: ["tck_wai_zui", "tck_kuang_xiao"],
      img: "extension/TCK/imgs/charactors/tck_jiutuntongzi.jpg",
    },
    "tck_scp_999": {
      sex: "none",
      group: "tck_shou",
      hp: 3,
      maxHp: 3,
      skills: ["tck_gao_guai", "tck_yu_yue"],
      img: "extension/TCK/imgs/charactors/tck_scp_999.jpg",
    },
    "tck_shen_jiaxu": {
      sex: "male",
      group: "shen",
      hp: 3,
      maxHp: 3,
      skills: ["tck_shen_wei_mu", "tck_shen_jue_sha"],
      img: "extension/TCK/imgs/charactors/tck_shen_jiaxu.jpg",
    },
    "tck_tongyuan": {
      sex: "male",
      group: "qun",
      hp: 4,
      maxHp: 4,
      skills: ["tck_chao_feng", "tck_chuan_cheng"],
      img: "extension/TCK/imgs/charactors/tck_tongyuan.jpg",
    },
    "tck_buzhihuo": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_li_huo", "tck_huo_zhao", "tck_huo_ze", "tck_yu_huo"],
      img: "extension/TCK/imgs/charactors/tck_buzhihuo.jpg",
    },
    "tck_jiliangjiying": {
      sex: "male",
      group: "tck_jo",
      hp: 3,
      maxHp: 3,
      skills: ["tck_di_1_zha_dan", "tck_chuan_xin_gong_ji", "tck_bai_zhe_shi_shen"],
      img: "extension/TCK/imgs/charactors/tck_jiliangjiying.jpg",
    },
    "tck_qiaoni": {
      sex: "male",
      group: "tck_qiao",
      hp: 2,
      maxHp: 2,
      skills: ["tck_ma_shu", "tck_ya_1", "tck_ya_2", "tck_ya_3", "tck_ya_4"],
      img: "extension/TCK/imgs/charactors/tck_qiaoni.jpg",
    },
    "tck_chird": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_ba_ling", "tck_dou_wu"],
      img: "extension/TCK/imgs/charactors/tck_chird.jpg",
    },
    "tck_scp_075": {
      sex: "none",
      group: "tck_shou",
      hp: 4,
      maxHp: 4,
      skills: ["tck_suan_ye"],
      img: "extension/TCK/imgs/charactors/tck_scp_075.jpg",
    },
    "tck_tiansuohaoer": {
      sex: "male",
      group: "tck_chou",
      hp: 3,
      maxHp: 3,
      skills: ["tck_heng_heng", "tck_aaa"],
      img: "extension/TCK/imgs/charactors/tck_tiansuohaoer.jpg",
    },
    "tck_liweisi": {
      sex: "male",
      group: "tck_jia_mian",
      hp: 4,
      maxHp: 4,
      skills: ["tck_e_mo"],
      img: "extension/TCK/imgs/charactors/tck_liweisi.jpg",
    },
    "tck_guojia": {
      sex: "male",
      group: "wei",
      hp: 3,
      maxHp: 3,
      skills: ["tck_yi_ji", "tck_tian_du"],
      img: "extension/TCK/imgs/charactors/tck_guojia.jpg",
    },
    "tck_liaohua": {
      sex: "male",
      group: "shu",
      hp: 4,
      maxHp: 4,
      skills: ["tck_dang_xian", "tck_fu_li"],
      img: "extension/TCK/imgs/charactors/tck_liaohua.jpg",
    },
    "tck_scp_6999": {
      sex: "none",
      group: "tck_shou",
      hp: 5,
      maxHp: 5,
      skills: ["tck_jin_zhu", "tck_wu_zhu", "tck_ju_zhu"],
      img: "extension/TCK/imgs/charactors/tck_scp_6999.jpg",
    },
    "tck_Vlong": {
      sex: "none",
      group: "tck_long",
      hp: 3,
      maxHp: 3,
      skills: ["tck_V_zhi_li"],
      img: "extension/TCK/imgs/charactors/tck_Vlong.jpg",
    },
    "tck_hj_zhouyu": {
      sex: "male",
      group: "wu",
      hp: 4,
      maxHp: 4,
      skills: ["tck_hj_ying_zi", "tck_hj_fan_jian"],
      img: "extension/TCK/imgs/charactors/tck_hj_zhouyu.jpg",
    },
    "tck_yinyangyan": {
      sex: "none",
      group: "tck_luan_ru",
      hp: 2,
      maxHp: 2,
      skills: ["tck_yin_yang"],
      img: "extension/TCK/imgs/charactors/tck_yinyangyan.jpg",
    },
    "tck_lingcao": {
      sex: "male",
      group: "wu",
      hp: 4,
      maxHp: 4,
      skills: ["tck_du_jin", "tck_qing_zhou"],
      img: "extension/TCK/imgs/charactors/tck_lingcao.jpg",
    },
    "tck_huatuo": {
      sex: "male",
      group: "qun",
      hp: 3,
      maxHp: 3,
      skills: ["tck_ji_jiu", "tck_qing_nang"],
      img: "extension/TCK/imgs/charactors/tck_huatuo.jpg",
    },
    "tck_wonianjiqingqinggongzijiudadao3200yigeyue": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 3,
      maxHp: 3,
      skills: ["tck_nian_qing", "tck_3200"],
      img: "extension/TCK/imgs/charactors/tck_wonianjiqingqinggongzijiudadao3200yigeyue.jpg",
    },
    "tck_laoba": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 5,
      maxHp: 5,
      skills: ["tck_chi_ba_ba"],
      img: "extension/TCK/imgs/charactors/tck_laoba.jpg",
    },
    "tck_gumingdilian": {
      sex: "female",
      group: "tck_jue",
      hp: 4,
      maxHp: 4,
      skills: ["tck_jue_zhi_tong", "tck_514", "tck_yao_guai_shao_nv"],
      img: "extension/TCK/imgs/charactors/tck_gumingdilian.jpg",
    },
    "tck_laofeng": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_xia_du", "tck_jue_bao"],
      img: "extension/TCK/imgs/charactors/tck_laofeng.jpg",
    },
    "tck_laofeng": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_xia_du", "tck_jue_bao"],
      img: "extension/TCK/imgs/charactors/tck_laofeng.jpg",
    },
    "tck_xiangjiaojun": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_zi_you"],
      img: "extension/TCK/imgs/charactors/tck_xiangjiaojun.jpg",
    },
    "tck_moduoluoyinqinai": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_mi_shen", "tck_men_fei", "tck_cang"],
      img: "extension/TCK/imgs/charactors/tck_moduoluoyinqinai.jpg",
    },

    //重制版
    "tck_r_zpn": {
      sex: "male",
      group: "tck_luan_ru",
      hp: 4,
      maxHp: 4,
      skills: ["tck_r_ji_rou", "tck_r_you_huo"],
      img: "extension/TCK/imgs/charactors/tck_r_zpn.jpg",
    },
    "tck_r_momo": {
      sex: "female",
      group: "tck_luan_ru",
      hp: 5,
      maxHp: 5,
      skills: ["tck_r_fu_xin", "tck_r_hua_tian"],
      img: "extension/TCK/imgs/charactors/tck_r_momo.jpg",
    },

  },
  translate: {
    "tck_moduoluoyinqinai": "摩多罗隐歧奈",
    "tck_xiangjiaojun": "香蕉君",
    "tck_laofeng": "老冯",
    "tck_gumingdilian": "古明地恋",
    "tck_laoba": "老八",
    "tck_wonianjiqingqinggongzijiudadao3200yigeyue": "我年纪轻轻工资就达到3200一个月",
    "tck_huatuo": "华佗",
    "tck_lingcao": "凌操",
    "tck_yinyangyan": "阴阳眼",
    "tck_hj_zhouyu": "周瑜",
    "tck_Vlong": "V龙",
    "tck_scp_6999": "SCP6999",
    "tck_guojia": "郭嘉",
    "tck_liweisi": "利维斯",
    "tck_tiansuohaoer": "田所浩二",
    "tck_scp_075": "SCP075",
    "tck_chird": "Chird",
    "tck_qiaoni": "乔尼",
    "tck_jiliangjiying": "吉良吉影",
    "tck_buzhihuo": "不知火",
    "tck_tongyuan": "童渊",
    "tck_liaohua": "廖化",
    "tck_shen_jiaxu": "贾诩",
    "tck_r_momo": "漠漠",
    "tck_scp_999": "SCP999",
    "tck_jiutuntongzi": "酒吞童子",
    "tck_fengfeisha": "风飞沙",
    "tck_scp_001_wjlt": "SCP001",
    "tck_guanyu_zhangfei": "关羽 张飞",
    "tck_fhz": "傅还政",
    "tck_wuyumolisha": "雾雨魔理沙",
    "tck_bachidaren": "八尺大人",
    "tck_rkshs_fuchuangzi": "附窗子",
    "tck_ban": "班",
    "tck_r_zpn": "朱沛宁",
    "tck_spc_173": "SPC173",
    "tck_scp_035": "SCP035",
    "tck_sp_sunshangxiang": "SP孙尚香",
    "tck_marry": "Marry",
    "tck_aoerjia": "奥尔加",
    "tck_rkshs_IB": "伊布",
    "TCK": "TCK",
    "tck_wzh": "王子含",
    "tck_xing_wzh": "星王子含",
    "tch_hwj_wzh": "洪玮健 王子含",
    "tck_yzxd_wzh": "王子含（泳装限定）",
    "tck_hxc": "胡新淳",
    "tck_gh": "高杭",
    "tck_yjc": "杨俊程",
    "tck_scp_173": "SCP173",
    "tck_luan_ru_pack": "乱入",
    "tck_san_guo_pack": "三国",
    "tck_r_pack": "重制版",
    "tck_hj_caozhang": "曹彰",
    "tck_hj_weiyan": "魏延",
    "tck_hj_huanggai": "黄盖",
    "tck_pmk_ailian": "艾莲",
  },
  characterTitle: {
    "tck_moduoluoyinqinai": "摸多了硬起来",
    "tck_xiangjiaojun": "自由的那个男人",
    "tck_laofeng": "高级特工",
    "tck_gumingdilian": "514",
    "tck_laoba": "美食家",
    "tck_wonianjiqingqinggongzijiudadao3200yigeyue": "3200",
    "tck_huatuo": "神医在世",
    "tck_lingcao": "轻舟独进",
    "tck_yinyangyan": "☯︎",
    "tck_hj_zhouyu": "东吴大都督",
    "tck_Vlong": "胜利龙",
    "tck_scp_6999": "更近吾主",
    "tck_guojia": "天妒英才",
    "tck_liweisi": "50周年纪念",
    "tck_tiansuohaoer": "先辈",
    "tck_scp_075": "腐蚀性蜗牛",
    "tck_chird": "美式霸凌",
    "tck_qiaoni": "三战神",
    "tck_jiliangjiying": "变态杀人狂",
    "tck_tongyuan": "百鸟朝凤",
    "tck_liaohua": "蜀汉忠义",
    "tck_shen_jiaxu": "文和乱武",
    "tck_r_momo": "小猫咪",
    "tck_scp_999": "痒痒怪",
    "tck_jiutuntongzi": "鬼王",
    "tck_scp_001_wjlt": "无尽楼梯",
    "tck_guanyu_zhangfei": "桃园之义",
    "tck_fhz": "画家",
    "tck_wuyumolisha": "普通的魔法使",
    "tck_bachidaren": "都市传说",
    "tck_ban": "老师",
    "tck_r_zpn": "肌肉",
    "tck_spc_173": "爱学习的鲨鱼",
    "tck_scp_035": "丢失的数字",
    "tck_marry": "画中人",
    "tck_aoerjia": "团长",
    "tck_rkshs_fuchuangzi": "日恐四幻神",
    "tck_rkshs_IB": "日恐四幻神",
    "tck_pmk_ailian": "贫民窟",
    "tck_wzh": "劳动之星",
    "tck_xing_wzh": "嬉皮笑脸",
    "tch_hwj_wzh": "上阵父子兵",
    "tck_yzxd_wzh": "贪生怕死",
    "tck_scp_173": "雕像",
    "tck_gh": "吉他手",
    "tck_hj_caozhang": "黄须儿",
    "tck_hj_weiyan": "饮血啖肉<br/>极简线条",
    "tck_hj_huanggai": "好舒服啊",
    "tck_hxc": "雅湖の鷄",
    "tck_yjc": "沈以诚",
  },
  characterSort: {
    "TCK": {
      //乱入
      "tck_luan_ru_pack": ["tck_wzh", "tch_hwj_wzh",
        "tck_yzxd_wzh", "tck_gh", "tck_scp_173",
        "tck_hxc", "tck_yjc", "tck_pmk_ailian",
        "tck_rkshs_IB", "tck_aoerjia", "tck_marry",
        "tck_scp_035", "tck_spc_173", "tck_ban",
        "tck_rkshs_fuchuangzi", "tck_bachidaren",
        "tck_wuyumolisha", "tck_fhz", "tck_scp_001_wjlt",
        "tck_fengfeisha", "tck_jiutuntongzi", "tck_scp_999",
        "tck_buzhihuo", "tck_jiliangjiying", "tck_qiaoni",
        "tck_chird", "tck_scp_075", "tck_tiansuohaoer",
        "tck_liweisi", "tck_scp_6999", "tck_Vlong",
        "tck_yinyangyan", "tck_wonianjiqingqinggongzijiudadao3200yigeyue",
        "tck_laoba", "tck_gumingdilian", "tck_laofeng",
        "tck_xiangjiaojun", "tck_moduoluoyinqinai",

      ],

      //三国
      "tck_san_guo_pack": ["tck_hj_caozhang", "tck_hj_weiyan",
        "tck_hj_huanggai", "tck_sp_sunshangxiang",
        "tck_guanyu_zhangfei", "tck_shen_jiaxu", "tck_liaohua",
        "tck_tongyuan", "tck_guojia", "tck_hj_zhouyu",
        "tck_lingcao", "tck_huatuo",
      ],

      //重制版
      "tck_r_pack": ["tck_r_zpn", "tck_r_momo",]

    }
  }
}

export default characters